version: "3.8"
services:
  db:
    image: mongo
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"

  backend:
    env_file:
      - .env
    build:
      context: ./docker_node
      dockerfile: backend.dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./docker_node/src:/app/src

  frontend:
    build:
      context: ./docker_react
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    volumes:
      - ./docker_react/src:/app/src

volumes:
  db_data:
